name: timezone-check
description: Set RUN_BOOKING based on scheduled hour in Europe/London
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        CRON="${{ github.event.schedule }}"
        if [ -z "$CRON" ]; then
          echo "RUN_BOOKING=false" >> "$GITHUB_ENV"
          exit 0
        fi
        CRON_HOUR=$(echo "$CRON" | awk '{print $2}')
        LOCAL_HOUR=$(TZ=Europe/London date +%H)
        SCHEDULE_LOCAL_HOUR=$(TZ=Europe/London date -d "today ${CRON_HOUR}:00 UTC" +%H)
        [ "$LOCAL_HOUR" = "$SCHEDULE_LOCAL_HOUR" ] && echo "RUN_BOOKING=true" >> "$GITHUB_ENV" || echo "RUN_BOOKING=false" >> "$GITHUB_ENV"
